build:
  cuda_version: "11.8.0"
  system_packages:
    - "libssl-dev"
    - "libx11-6"
    - "libxext6"
    - "libgl1-mesa-glx"
    - "ninja-build"
    - "git"
  python_packages:
    - "torch==2.4.0"
    - "torchvision==0.19.0"
    - "pytorch-cuda==11.8"
    - "pillow"
    - "imageio"
    - "imageio-ffmpeg"
    - "tqdm"
    - "easydict"
    - "opencv-python-headless"
    - "scipy"
    - "ninja"
    - "rembg"
    - "onnxruntime"
    - "trimesh"
    - "xatlas"
    - "pyvista"
    - "pymeshfix"
    - "igraph"
    - "transformers"
    - "xformers==0.0.27.post2"
    - "flash-attn"
    - "spconv-cu118"
    - "kaolin"
    - "gradio==4.44.1"
    - "gradio_litmodel3d==0.0.1"